/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spa_salon_frontdesk;

/**
 *
 * @author Andot
 */
public class AdminDesk extends javax.swing.JFrame {

    /**
     * Creates new form AdminDesk
     */
    public AdminDesk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddSalonServices = new javax.swing.JButton();
        btnAddSpaServices = new javax.swing.JButton();
        btnMngSpaServices = new javax.swing.JButton();
        btnMngSalonServices = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Desk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnAddSalonServices.setBackground(new java.awt.Color(204, 204, 204));
        btnAddSalonServices.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btnAddSalonServices.setText("Add Salon Services");
        btnAddSalonServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSalonServicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSalonServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 319, -1));

        btnAddSpaServices.setBackground(new java.awt.Color(204, 204, 204));
        btnAddSpaServices.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btnAddSpaServices.setText("Add Spa Services");
        btnAddSpaServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSpaServicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSpaServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 319, -1));

        btnMngSpaServices.setBackground(new java.awt.Color(204, 204, 204));
        btnMngSpaServices.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btnMngSpaServices.setText("Manage Spa Services");
        btnMngSpaServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSpaServicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMngSpaServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 319, -1));

        btnMngSalonServices.setBackground(new java.awt.Color(204, 204, 204));
        btnMngSalonServices.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btnMngSalonServices.setText("Manage Salon Services");
        btnMngSalonServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSalonServicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMngSalonServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSalonServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSalonServicesActionPerformed
        AddSalonServicesFrame asf = new AddSalonServicesFrame();
        asf.setVisible(true);
    }//GEN-LAST:event_btnAddSalonServicesActionPerformed

    private void btnAddSpaServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSpaServicesActionPerformed
        AddSpaServicesFrame assf = new AddSpaServicesFrame();
        assf.setVisible(true);
    }//GEN-LAST:event_btnAddSpaServicesActionPerformed

    private void btnMngSpaServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSpaServicesActionPerformed
        ManageSpaServicesFrame asf = new ManageSpaServicesFrame();
        asf.setVisible(true);
    }//GEN-LAST:event_btnMngSpaServicesActionPerformed

    private void btnMngSalonServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSalonServicesActionPerformed
         ManageSalonServicesFrame assf = new ManageSalonServicesFrame();
        assf.setVisible(true);
    }//GEN-LAST:event_btnMngSalonServicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSalonServices;
    private javax.swing.JButton btnAddSpaServices;
    private javax.swing.JButton btnMngSalonServices;
    private javax.swing.JButton btnMngSpaServices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
